[package]
name = "hlab"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.12"
futures = "0.3"
warp = "0.3"
serde = { version = "1.0.152", features = ["derive"] }
sysinfo = "0.28.0"